apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeserver
spec:
  selector:
    matchLabels:
      app: nodeserver
  replicas: 1
  template:
    metadata:
      labels:
        app: nodeserver
    spec:
      containers:
        - name: nodeserver
          image: nodeserver
          ports:
            - containerPort: 3000
