name: CD Gitops

on:
  push:
    branches: [main]

jobs:
  buld:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      users: actions/checkout@v2 

    - name: Build and push image to Dockerhub
      users: docker/build-push-actions@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_USERNAME }}/gitopsfc
        tags: ${{ github.sha }}, latest

